# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer_UIs/import_db_mat.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportDB(object):
    def setupUi(self, ImportDB):
        ImportDB.setObjectName("ImportDB")
        ImportDB.resize(432, 165)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImportDB.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportDB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(ImportDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.choose_file_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_file_button.sizePolicy().hasHeightForWidth())
        self.choose_file_button.setSizePolicy(sizePolicy)
        self.choose_file_button.setObjectName("choose_file_button")
        self.gridLayout.addWidget(self.choose_file_button, 0, 0, 1, 1)
        self.chosen_file_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chosen_file_label.sizePolicy().hasHeightForWidth())
        self.chosen_file_label.setSizePolicy(sizePolicy)
        self.chosen_file_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chosen_file_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chosen_file_label.setText("")
        self.chosen_file_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chosen_file_label.setObjectName("chosen_file_label")
        self.gridLayout.addWidget(self.chosen_file_label, 0, 2, 1, 1)
        self.mat_name_label = QtWidgets.QLabel(self.frame_2)
        self.mat_name_label.setObjectName("mat_name_label")
        self.gridLayout.addWidget(self.mat_name_label, 1, 0, 1, 1)
        self.mat_name_edit = QtWidgets.QLineEdit(self.frame_2)
        self.mat_name_edit.setObjectName("mat_name_edit")
        self.gridLayout.addWidget(self.mat_name_edit, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(ImportDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.units_label = QtWidgets.QLabel(self.frame)
        self.units_label.setObjectName("units_label")
        self.horizontalLayout.addWidget(self.units_label)
        self.unit_combobox = QtWidgets.QComboBox(self.frame)
        self.unit_combobox.setObjectName("unit_combobox")
        self.horizontalLayout.addWidget(self.unit_combobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.import_button = QtWidgets.QPushButton(self.frame)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout.addWidget(self.import_button)
        self.preview_button = QtWidgets.QPushButton(self.frame)
        self.preview_button.setObjectName("preview_button")
        self.horizontalLayout.addWidget(self.preview_button)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ImportDB)
        QtCore.QMetaObject.connectSlotsByName(ImportDB)

    def retranslateUi(self, ImportDB):
        _translate = QtCore.QCoreApplication.translate
        ImportDB.setWindowTitle(_translate("ImportDB", "Import Material"))
        self.choose_file_button.setText(_translate("ImportDB", "Choose File"))
        self.mat_name_label.setText(_translate("ImportDB", "Material Name"))
        self.units_label.setText(_translate("ImportDB", "Units:"))
        self.import_button.setText(_translate("ImportDB", "Import"))
        self.preview_button.setText(_translate("ImportDB", "Preview"))
