# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer_UIs/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SMM_Window(object):
    def setupUi(self, SMM_Window):
        SMM_Window.setObjectName("SMM_Window")
        SMM_Window.resize(752, 595)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        SMM_Window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SMM_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SMM_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setObjectName("tab_widget")
        self.simulation_tab = QtWidgets.QWidget()
        self.simulation_tab.setObjectName("simulation_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.simulation_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sim_tab_ref_frame = QtWidgets.QFrame(self.simulation_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_ref_frame.sizePolicy().hasHeightForWidth())
        self.sim_tab_ref_frame.setSizePolicy(sizePolicy)
        self.sim_tab_ref_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_tab_ref_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_tab_ref_frame.setLineWidth(2)
        self.sim_tab_ref_frame.setObjectName("sim_tab_ref_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sim_tab_ref_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sim_tab_ref_label = QtWidgets.QLabel(self.sim_tab_ref_frame)
        self.sim_tab_ref_label.setObjectName("sim_tab_ref_label")
        self.horizontalLayout.addWidget(self.sim_tab_ref_label)
        spacerItem = QtWidgets.QSpacerItem(210, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sim_tab_ref_n_label = QtWidgets.QLabel(self.sim_tab_ref_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sim_tab_ref_n_label.setFont(font)
        self.sim_tab_ref_n_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_ref_n_label.setObjectName("sim_tab_ref_n_label")
        self.horizontalLayout.addWidget(self.sim_tab_ref_n_label)
        self.sim_tab_ref_n = QtWidgets.QLineEdit(self.sim_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_ref_n.setFont(font)
        self.sim_tab_ref_n.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_ref_n.setObjectName("sim_tab_ref_n")
        self.horizontalLayout.addWidget(self.sim_tab_ref_n)
        self.sim_tab_ref_k_label = QtWidgets.QLabel(self.sim_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_ref_k_label.setFont(font)
        self.sim_tab_ref_k_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_ref_k_label.setObjectName("sim_tab_ref_k_label")
        self.horizontalLayout.addWidget(self.sim_tab_ref_k_label)
        self.sim_tab_ref_k = QtWidgets.QLineEdit(self.sim_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_ref_k.setFont(font)
        self.sim_tab_ref_k.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_ref_k.setObjectName("sim_tab_ref_k")
        self.horizontalLayout.addWidget(self.sim_tab_ref_k)
        self.verticalLayout_2.addWidget(self.sim_tab_ref_frame)
        self.sim_tab_sim_frame = QtWidgets.QFrame(self.simulation_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_frame.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_frame.setSizePolicy(sizePolicy)
        self.sim_tab_sim_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_tab_sim_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_tab_sim_frame.setLineWidth(2)
        self.sim_tab_sim_frame.setObjectName("sim_tab_sim_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sim_tab_sim_frame)
        self.gridLayout_2.setContentsMargins(10, 0, 10, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sim_tab_sim_mat_size1 = QtWidgets.QLineEdit(self.sim_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_mat_size1.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_mat_size1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_sim_mat_size1.setFont(font)
        self.sim_tab_sim_mat_size1.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_sim_mat_size1.setObjectName("sim_tab_sim_mat_size1")
        self.gridLayout_2.addWidget(self.sim_tab_sim_mat_size1, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.sim_tab_sim_mat1 = QtWidgets.QComboBox(self.sim_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_mat1.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_mat1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_sim_mat1.setFont(font)
        self.sim_tab_sim_mat1.setObjectName("sim_tab_sim_mat1")
        self.gridLayout_2.addWidget(self.sim_tab_sim_mat1, 1, 0, 1, 1)
        self.sim_tab_sim_mat2 = QtWidgets.QComboBox(self.sim_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_mat2.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_mat2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_sim_mat2.setFont(font)
        self.sim_tab_sim_mat2.setObjectName("sim_tab_sim_mat2")
        self.gridLayout_2.addWidget(self.sim_tab_sim_mat2, 2, 0, 1, 1)
        self.sim_tab_sim_size_label = QtWidgets.QLabel(self.sim_tab_sim_frame)
        self.sim_tab_sim_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_sim_size_label.setObjectName("sim_tab_sim_size_label")
        self.gridLayout_2.addWidget(self.sim_tab_sim_size_label, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.sim_tab_sim_mat_label = QtWidgets.QLabel(self.sim_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_mat_label.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_mat_label.setSizePolicy(sizePolicy)
        self.sim_tab_sim_mat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_sim_mat_label.setObjectName("sim_tab_sim_mat_label")
        self.gridLayout_2.addWidget(self.sim_tab_sim_mat_label, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.sim_tab_sim_mat_size2 = QtWidgets.QLineEdit(self.sim_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_sim_mat_size2.sizePolicy().hasHeightForWidth())
        self.sim_tab_sim_mat_size2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_sim_mat_size2.setFont(font)
        self.sim_tab_sim_mat_size2.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_sim_mat_size2.setObjectName("sim_tab_sim_mat_size2")
        self.gridLayout_2.addWidget(self.sim_tab_sim_mat_size2, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.sim_tab_sim_frame)
        self.sim_tab_trn_frame = QtWidgets.QFrame(self.simulation_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_trn_frame.sizePolicy().hasHeightForWidth())
        self.sim_tab_trn_frame.setSizePolicy(sizePolicy)
        self.sim_tab_trn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_tab_trn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_tab_trn_frame.setLineWidth(2)
        self.sim_tab_trn_frame.setObjectName("sim_tab_trn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sim_tab_trn_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sim_tab_trn_label = QtWidgets.QLabel(self.sim_tab_trn_frame)
        self.sim_tab_trn_label.setObjectName("sim_tab_trn_label")
        self.horizontalLayout_2.addWidget(self.sim_tab_trn_label)
        spacerItem4 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.sim_tab_trn_n_label = QtWidgets.QLabel(self.sim_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sim_tab_trn_n_label.setFont(font)
        self.sim_tab_trn_n_label.setObjectName("sim_tab_trn_n_label")
        self.horizontalLayout_2.addWidget(self.sim_tab_trn_n_label)
        self.sim_tab_trn_n = QtWidgets.QLineEdit(self.sim_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sim_tab_trn_n.setFont(font)
        self.sim_tab_trn_n.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_trn_n.setObjectName("sim_tab_trn_n")
        self.horizontalLayout_2.addWidget(self.sim_tab_trn_n)
        self.sim_tab_trn_k_label = QtWidgets.QLabel(self.sim_tab_trn_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_tab_trn_k_label.setFont(font)
        self.sim_tab_trn_k_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_trn_k_label.setObjectName("sim_tab_trn_k_label")
        self.horizontalLayout_2.addWidget(self.sim_tab_trn_k_label)
        self.sim_tab_trn_k = QtWidgets.QLineEdit(self.sim_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sim_tab_trn_k.setFont(font)
        self.sim_tab_trn_k.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_tab_trn_k.setObjectName("sim_tab_trn_k")
        self.horizontalLayout_2.addWidget(self.sim_tab_trn_k)
        self.verticalLayout_2.addWidget(self.sim_tab_trn_frame)
        spacerItem5 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem5)
        self.sim_tab_buttons_frame = QtWidgets.QFrame(self.simulation_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_tab_buttons_frame.sizePolicy().hasHeightForWidth())
        self.sim_tab_buttons_frame.setSizePolicy(sizePolicy)
        self.sim_tab_buttons_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sim_tab_buttons_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sim_tab_buttons_frame.setLineWidth(0)
        self.sim_tab_buttons_frame.setObjectName("sim_tab_buttons_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sim_tab_buttons_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sim_tab_add_layer_button = QtWidgets.QPushButton(self.sim_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sim_tab_add_layer_button.setFont(font)
        self.sim_tab_add_layer_button.setObjectName("sim_tab_add_layer_button")
        self.horizontalLayout_3.addWidget(self.sim_tab_add_layer_button)
        self.sim_tab_rem_layer_button = QtWidgets.QPushButton(self.sim_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sim_tab_rem_layer_button.setFont(font)
        self.sim_tab_rem_layer_button.setObjectName("sim_tab_rem_layer_button")
        self.horizontalLayout_3.addWidget(self.sim_tab_rem_layer_button)
        self.sim_tab_export_button = QtWidgets.QPushButton(self.sim_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sim_tab_export_button.setFont(font)
        self.sim_tab_export_button.setObjectName("sim_tab_export_button")
        self.horizontalLayout_3.addWidget(self.sim_tab_export_button)
        self.sim_tab_clear_button = QtWidgets.QPushButton(self.sim_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sim_tab_clear_button.setFont(font)
        self.sim_tab_clear_button.setObjectName("sim_tab_clear_button")
        self.horizontalLayout_3.addWidget(self.sim_tab_clear_button)
        spacerItem6 = QtWidgets.QSpacerItem(191, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.sim_tab_buttons_frame)
        self.sim_tab_sim_button = QtWidgets.QPushButton(self.simulation_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sim_tab_sim_button.setFont(font)
        self.sim_tab_sim_button.setObjectName("sim_tab_sim_button")
        self.verticalLayout_2.addWidget(self.sim_tab_sim_button)
        self.tab_widget.addTab(self.simulation_tab, "")
        self.optimizatio_tab = QtWidgets.QWidget()
        self.optimizatio_tab.setObjectName("optimizatio_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.optimizatio_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.opt_tab_ref_frame = QtWidgets.QFrame(self.optimizatio_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_ref_frame.sizePolicy().hasHeightForWidth())
        self.opt_tab_ref_frame.setSizePolicy(sizePolicy)
        self.opt_tab_ref_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opt_tab_ref_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opt_tab_ref_frame.setLineWidth(2)
        self.opt_tab_ref_frame.setObjectName("opt_tab_ref_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.opt_tab_ref_frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.opt_tab_ref_label = QtWidgets.QLabel(self.opt_tab_ref_frame)
        self.opt_tab_ref_label.setObjectName("opt_tab_ref_label")
        self.horizontalLayout_8.addWidget(self.opt_tab_ref_label)
        spacerItem7 = QtWidgets.QSpacerItem(210, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.opt_tab_ref_n_label = QtWidgets.QLabel(self.opt_tab_ref_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.opt_tab_ref_n_label.setFont(font)
        self.opt_tab_ref_n_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_ref_n_label.setObjectName("opt_tab_ref_n_label")
        self.horizontalLayout_8.addWidget(self.opt_tab_ref_n_label)
        self.opt_tab_ref_n = QtWidgets.QLineEdit(self.opt_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_ref_n.setFont(font)
        self.opt_tab_ref_n.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_ref_n.setObjectName("opt_tab_ref_n")
        self.horizontalLayout_8.addWidget(self.opt_tab_ref_n)
        self.opt_tab_ref_k_label = QtWidgets.QLabel(self.opt_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_ref_k_label.setFont(font)
        self.opt_tab_ref_k_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_ref_k_label.setObjectName("opt_tab_ref_k_label")
        self.horizontalLayout_8.addWidget(self.opt_tab_ref_k_label)
        self.opt_tab_ref_k = QtWidgets.QLineEdit(self.opt_tab_ref_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_ref_k.setFont(font)
        self.opt_tab_ref_k.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_ref_k.setObjectName("opt_tab_ref_k")
        self.horizontalLayout_8.addWidget(self.opt_tab_ref_k)
        self.verticalLayout_4.addWidget(self.opt_tab_ref_frame)
        self.opt_tab_sim_frame = QtWidgets.QFrame(self.optimizatio_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_frame.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_frame.setSizePolicy(sizePolicy)
        self.opt_tab_sim_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opt_tab_sim_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opt_tab_sim_frame.setLineWidth(2)
        self.opt_tab_sim_frame.setObjectName("opt_tab_sim_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.opt_tab_sim_frame)
        self.gridLayout_4.setContentsMargins(10, 0, 10, 20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.opt_tab_sim_mat_size_min2 = QtWidgets.QLineEdit(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat_size_min2.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat_size_min2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat_size_min2.setFont(font)
        self.opt_tab_sim_mat_size_min2.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_sim_mat_size_min2.setObjectName("opt_tab_sim_mat_size_min2")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_min2, 2, 2, 1, 1)
        self.opt_tab_sim_mat_size_max2 = QtWidgets.QLineEdit(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat_size_max2.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat_size_max2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat_size_max2.setFont(font)
        self.opt_tab_sim_mat_size_max2.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_sim_mat_size_max2.setObjectName("opt_tab_sim_mat_size_max2")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_max2, 2, 3, 1, 1)
        self.opt_tab_sim_mat_size_max_label = QtWidgets.QLabel(self.opt_tab_sim_frame)
        self.opt_tab_sim_mat_size_max_label.setObjectName("opt_tab_sim_mat_size_max_label")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_max_label, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        self.opt_tab_sim_mat_size_min_label = QtWidgets.QLabel(self.opt_tab_sim_frame)
        self.opt_tab_sim_mat_size_min_label.setObjectName("opt_tab_sim_mat_size_min_label")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_min_label, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 1, 1, 1)
        self.opt_tab_sim_mat1 = QtWidgets.QComboBox(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat1.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat1.setFont(font)
        self.opt_tab_sim_mat1.setObjectName("opt_tab_sim_mat1")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat1, 1, 0, 1, 1)
        self.opt_tab_sim_mat_size_max1 = QtWidgets.QLineEdit(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat_size_max1.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat_size_max1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat_size_max1.setFont(font)
        self.opt_tab_sim_mat_size_max1.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_sim_mat_size_max1.setObjectName("opt_tab_sim_mat_size_max1")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_max1, 1, 3, 1, 1)
        self.opt_tab_sim_mat_label = QtWidgets.QLabel(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat_label.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat_label.setSizePolicy(sizePolicy)
        self.opt_tab_sim_mat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_sim_mat_label.setObjectName("opt_tab_sim_mat_label")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_label, 0, 0, 1, 1)
        self.opt_tab_sim_mat_size_min1 = QtWidgets.QLineEdit(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat_size_min1.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat_size_min1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat_size_min1.setFont(font)
        self.opt_tab_sim_mat_size_min1.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_sim_mat_size_min1.setObjectName("opt_tab_sim_mat_size_min1")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat_size_min1, 1, 2, 1, 1)
        self.opt_tab_sim_mat2 = QtWidgets.QComboBox(self.opt_tab_sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_sim_mat2.sizePolicy().hasHeightForWidth())
        self.opt_tab_sim_mat2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_sim_mat2.setFont(font)
        self.opt_tab_sim_mat2.setObjectName("opt_tab_sim_mat2")
        self.gridLayout_4.addWidget(self.opt_tab_sim_mat2, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.opt_tab_sim_frame)
        self.opt_tab_trn_frame = QtWidgets.QFrame(self.optimizatio_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_trn_frame.sizePolicy().hasHeightForWidth())
        self.opt_tab_trn_frame.setSizePolicy(sizePolicy)
        self.opt_tab_trn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opt_tab_trn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opt_tab_trn_frame.setLineWidth(2)
        self.opt_tab_trn_frame.setObjectName("opt_tab_trn_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.opt_tab_trn_frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.opt_tab_trn_label = QtWidgets.QLabel(self.opt_tab_trn_frame)
        self.opt_tab_trn_label.setObjectName("opt_tab_trn_label")
        self.horizontalLayout_10.addWidget(self.opt_tab_trn_label)
        spacerItem11 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.opt_tab_trn_n_label = QtWidgets.QLabel(self.opt_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.opt_tab_trn_n_label.setFont(font)
        self.opt_tab_trn_n_label.setObjectName("opt_tab_trn_n_label")
        self.horizontalLayout_10.addWidget(self.opt_tab_trn_n_label)
        self.opt_tab_trn_n = QtWidgets.QLineEdit(self.opt_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.opt_tab_trn_n.setFont(font)
        self.opt_tab_trn_n.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_trn_n.setObjectName("opt_tab_trn_n")
        self.horizontalLayout_10.addWidget(self.opt_tab_trn_n)
        self.opt_tab_trn_k_label = QtWidgets.QLabel(self.opt_tab_trn_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opt_tab_trn_k_label.setFont(font)
        self.opt_tab_trn_k_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_trn_k_label.setObjectName("opt_tab_trn_k_label")
        self.horizontalLayout_10.addWidget(self.opt_tab_trn_k_label)
        self.opt_tab_trn_k = QtWidgets.QLineEdit(self.opt_tab_trn_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.opt_tab_trn_k.setFont(font)
        self.opt_tab_trn_k.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_tab_trn_k.setObjectName("opt_tab_trn_k")
        self.horizontalLayout_10.addWidget(self.opt_tab_trn_k)
        self.verticalLayout_4.addWidget(self.opt_tab_trn_frame)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.opt_tab_buttons_frame = QtWidgets.QFrame(self.optimizatio_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tab_buttons_frame.sizePolicy().hasHeightForWidth())
        self.opt_tab_buttons_frame.setSizePolicy(sizePolicy)
        self.opt_tab_buttons_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.opt_tab_buttons_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.opt_tab_buttons_frame.setLineWidth(0)
        self.opt_tab_buttons_frame.setObjectName("opt_tab_buttons_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.opt_tab_buttons_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.opt_tab_add_layer_button = QtWidgets.QPushButton(self.opt_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.opt_tab_add_layer_button.setFont(font)
        self.opt_tab_add_layer_button.setObjectName("opt_tab_add_layer_button")
        self.horizontalLayout_11.addWidget(self.opt_tab_add_layer_button)
        self.opt_tab_rem_layer_button = QtWidgets.QPushButton(self.opt_tab_buttons_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.opt_tab_rem_layer_button.setFont(font)
        self.opt_tab_rem_layer_button.setObjectName("opt_tab_rem_layer_button")
        self.horizontalLayout_11.addWidget(self.opt_tab_rem_layer_button)
        spacerItem13 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.opt_progressBar = QtWidgets.QProgressBar(self.opt_tab_buttons_frame)
        self.opt_progressBar.setProperty("value", 25)
        self.opt_progressBar.setObjectName("opt_progressBar")
        self.horizontalLayout_11.addWidget(self.opt_progressBar)
        self.verticalLayout_4.addWidget(self.opt_tab_buttons_frame)
        self.opt_tab_sim_button = QtWidgets.QPushButton(self.optimizatio_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.opt_tab_sim_button.setFont(font)
        self.opt_tab_sim_button.setToolTip("")
        self.opt_tab_sim_button.setObjectName("opt_tab_sim_button")
        self.verticalLayout_4.addWidget(self.opt_tab_sim_button)
        self.tab_widget.addTab(self.optimizatio_tab, "")
        self.horizontalLayout_5.addWidget(self.tab_widget)
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame.sizePolicy().hasHeightForWidth())
        self.right_frame.setSizePolicy(sizePolicy)
        self.right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_frame.setLineWidth(0)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sim_param_frame_total = QtWidgets.QFrame(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_frame_total.sizePolicy().hasHeightForWidth())
        self.sim_param_frame_total.setSizePolicy(sizePolicy)
        self.sim_param_frame_total.setFrameShape(QtWidgets.QFrame.Box)
        self.sim_param_frame_total.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sim_param_frame_total.setLineWidth(2)
        self.sim_param_frame_total.setMidLineWidth(0)
        self.sim_param_frame_total.setObjectName("sim_param_frame_total")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sim_param_frame_total)
        self.verticalLayout.setContentsMargins(20, 5, 20, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.simulation_label = QtWidgets.QLabel(self.sim_param_frame_total)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.simulation_label.setFont(font)
        self.simulation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.simulation_label.setObjectName("simulation_label")
        self.verticalLayout.addWidget(self.simulation_label)
        self.sim_param_frame = QtWidgets.QFrame(self.sim_param_frame_total)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_frame.sizePolicy().hasHeightForWidth())
        self.sim_param_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sim_param_frame.setFont(font)
        self.sim_param_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sim_param_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sim_param_frame.setLineWidth(0)
        self.sim_param_frame.setObjectName("sim_param_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.sim_param_frame)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.sim_param_ptm_label = QtWidgets.QLabel(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_ptm_label.sizePolicy().hasHeightForWidth())
        self.sim_param_ptm_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_ptm_label.setFont(font)
        self.sim_param_ptm_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_ptm_label.setObjectName("sim_param_ptm_label")
        self.gridLayout.addWidget(self.sim_param_ptm_label, 4, 1, 1, 1)
        self.sim_param_phi_label = QtWidgets.QLabel(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_phi_label.sizePolicy().hasHeightForWidth())
        self.sim_param_phi_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_phi_label.setFont(font)
        self.sim_param_phi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_phi_label.setObjectName("sim_param_phi_label")
        self.gridLayout.addWidget(self.sim_param_phi_label, 3, 1, 1, 1)
        self.sim_param_theta_label = QtWidgets.QLabel(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_theta_label.sizePolicy().hasHeightForWidth())
        self.sim_param_theta_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_theta_label.setFont(font)
        self.sim_param_theta_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_theta_label.setObjectName("sim_param_theta_label")
        self.gridLayout.addWidget(self.sim_param_theta_label, 2, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 1, 2, 1, 1)
        self.sim_param_lmb_min = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_lmb_min.sizePolicy().hasHeightForWidth())
        self.sim_param_lmb_min.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_lmb_min.setFont(font)
        self.sim_param_lmb_min.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_lmb_min.setObjectName("sim_param_lmb_min")
        self.gridLayout.addWidget(self.sim_param_lmb_min, 0, 3, 1, 1)
        self.sim_param_lmb_max_label = QtWidgets.QLabel(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_lmb_max_label.sizePolicy().hasHeightForWidth())
        self.sim_param_lmb_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_lmb_max_label.setFont(font)
        self.sim_param_lmb_max_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_lmb_max_label.setObjectName("sim_param_lmb_max_label")
        self.gridLayout.addWidget(self.sim_param_lmb_max_label, 1, 0, 1, 2)
        self.sim_param_pte = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_pte.sizePolicy().hasHeightForWidth())
        self.sim_param_pte.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_pte.setFont(font)
        self.sim_param_pte.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_pte.setObjectName("sim_param_pte")
        self.gridLayout.addWidget(self.sim_param_pte, 5, 3, 1, 1)
        self.sim_param_lmb_min_label = QtWidgets.QLabel(self.sim_param_frame)
        self.sim_param_lmb_min_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_lmb_min_label.sizePolicy().hasHeightForWidth())
        self.sim_param_lmb_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_lmb_min_label.setFont(font)
        self.sim_param_lmb_min_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_lmb_min_label.setObjectName("sim_param_lmb_min_label")
        self.gridLayout.addWidget(self.sim_param_lmb_min_label, 0, 0, 1, 2)
        self.sim_param_theta = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_theta.sizePolicy().hasHeightForWidth())
        self.sim_param_theta.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_theta.setFont(font)
        self.sim_param_theta.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_theta.setPlaceholderText("")
        self.sim_param_theta.setObjectName("sim_param_theta")
        self.gridLayout.addWidget(self.sim_param_theta, 2, 3, 1, 1)
        self.sim_param_ptm = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_ptm.sizePolicy().hasHeightForWidth())
        self.sim_param_ptm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_ptm.setFont(font)
        self.sim_param_ptm.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_ptm.setObjectName("sim_param_ptm")
        self.gridLayout.addWidget(self.sim_param_ptm, 4, 3, 1, 1)
        self.sim_param_pte_label = QtWidgets.QLabel(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_pte_label.sizePolicy().hasHeightForWidth())
        self.sim_param_pte_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_pte_label.setFont(font)
        self.sim_param_pte_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sim_param_pte_label.setObjectName("sim_param_pte_label")
        self.gridLayout.addWidget(self.sim_param_pte_label, 5, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 3, 2, 1, 1)
        self.sim_param_lmb_max = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_lmb_max.sizePolicy().hasHeightForWidth())
        self.sim_param_lmb_max.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_lmb_max.setFont(font)
        self.sim_param_lmb_max.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_lmb_max.setPlaceholderText("")
        self.sim_param_lmb_max.setObjectName("sim_param_lmb_max")
        self.gridLayout.addWidget(self.sim_param_lmb_max, 1, 3, 1, 1)
        self.sim_param_phi = QtWidgets.QLineEdit(self.sim_param_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_param_phi.sizePolicy().hasHeightForWidth())
        self.sim_param_phi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_phi.setFont(font)
        self.sim_param_phi.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_param_phi.setPlaceholderText("")
        self.sim_param_phi.setObjectName("sim_param_phi")
        self.gridLayout.addWidget(self.sim_param_phi, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.sim_param_frame)
        self.sim_param_ref_checkbox = QtWidgets.QCheckBox(self.sim_param_frame_total)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_ref_checkbox.setFont(font)
        self.sim_param_ref_checkbox.setChecked(False)
        self.sim_param_ref_checkbox.setObjectName("sim_param_ref_checkbox")
        self.verticalLayout.addWidget(self.sim_param_ref_checkbox)
        self.sim_param_trn_checkbox = QtWidgets.QCheckBox(self.sim_param_frame_total)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_trn_checkbox.setFont(font)
        self.sim_param_trn_checkbox.setChecked(False)
        self.sim_param_trn_checkbox.setObjectName("sim_param_trn_checkbox")
        self.verticalLayout.addWidget(self.sim_param_trn_checkbox)
        self.sim_param_abs_checkbox = QtWidgets.QCheckBox(self.sim_param_frame_total)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sim_param_abs_checkbox.setFont(font)
        self.sim_param_abs_checkbox.setChecked(True)
        self.sim_param_abs_checkbox.setObjectName("sim_param_abs_checkbox")
        self.verticalLayout.addWidget(self.sim_param_abs_checkbox)
        self.verticalLayout_3.addWidget(self.sim_param_frame_total)
        self.opt_res_text = QtWidgets.QTextBrowser(self.right_frame)
        self.opt_res_text.setObjectName("opt_res_text")
        self.verticalLayout_3.addWidget(self.opt_res_text)
        self.import_button = QtWidgets.QPushButton(self.right_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.import_button.setFont(font)
        self.import_button.setObjectName("import_button")
        self.verticalLayout_3.addWidget(self.import_button)
        self.horizontalLayout_5.addWidget(self.right_frame)
        SMM_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SMM_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SMM_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SMM_Window)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        SMM_Window.setStatusBar(self.statusbar)
        self.actionAdd_to_Database = QtWidgets.QAction(SMM_Window)
        self.actionAdd_to_Database.setObjectName("actionAdd_to_Database")
        self.actionRemove_from_Database = QtWidgets.QAction(SMM_Window)
        self.actionRemove_from_Database.setObjectName("actionRemove_from_Database")
        self.actionExit = QtWidgets.QAction(SMM_Window)
        self.actionExit.setObjectName("actionExit")
        self.actionView_Database = QtWidgets.QAction(SMM_Window)
        self.actionView_Database.setObjectName("actionView_Database")
        self.actionProperties = QtWidgets.QAction(SMM_Window)
        self.actionProperties.setObjectName("actionProperties")
        self.actionHelp = QtWidgets.QAction(SMM_Window)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(SMM_Window)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionProperties)
        self.menuFile.addAction(self.actionExit)
        self.menuDatabase.addAction(self.actionView_Database)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SMM_Window)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SMM_Window)
        SMM_Window.setTabOrder(self.tab_widget, self.opt_tab_ref_n)
        SMM_Window.setTabOrder(self.opt_tab_ref_n, self.opt_tab_ref_k)
        SMM_Window.setTabOrder(self.opt_tab_ref_k, self.opt_tab_trn_n)
        SMM_Window.setTabOrder(self.opt_tab_trn_n, self.opt_tab_trn_k)
        SMM_Window.setTabOrder(self.opt_tab_trn_k, self.opt_tab_add_layer_button)
        SMM_Window.setTabOrder(self.opt_tab_add_layer_button, self.opt_tab_rem_layer_button)
        SMM_Window.setTabOrder(self.opt_tab_rem_layer_button, self.opt_tab_sim_button)
        SMM_Window.setTabOrder(self.opt_tab_sim_button, self.sim_param_lmb_min)
        SMM_Window.setTabOrder(self.sim_param_lmb_min, self.sim_param_lmb_max)
        SMM_Window.setTabOrder(self.sim_param_lmb_max, self.sim_param_theta)
        SMM_Window.setTabOrder(self.sim_param_theta, self.sim_param_phi)
        SMM_Window.setTabOrder(self.sim_param_phi, self.sim_param_ptm)
        SMM_Window.setTabOrder(self.sim_param_ptm, self.sim_param_pte)
        SMM_Window.setTabOrder(self.sim_param_pte, self.sim_param_ref_checkbox)
        SMM_Window.setTabOrder(self.sim_param_ref_checkbox, self.sim_param_trn_checkbox)
        SMM_Window.setTabOrder(self.sim_param_trn_checkbox, self.sim_param_abs_checkbox)
        SMM_Window.setTabOrder(self.sim_param_abs_checkbox, self.opt_res_text)
        SMM_Window.setTabOrder(self.opt_res_text, self.import_button)
        SMM_Window.setTabOrder(self.import_button, self.opt_tab_sim_mat1)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat1, self.opt_tab_sim_mat_size_min1)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat_size_min1, self.opt_tab_sim_mat_size_max1)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat_size_max1, self.opt_tab_sim_mat2)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat2, self.opt_tab_sim_mat_size_min2)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat_size_min2, self.opt_tab_sim_mat_size_max2)
        SMM_Window.setTabOrder(self.opt_tab_sim_mat_size_max2, self.sim_tab_ref_n)
        SMM_Window.setTabOrder(self.sim_tab_ref_n, self.sim_tab_ref_k)
        SMM_Window.setTabOrder(self.sim_tab_ref_k, self.sim_tab_trn_n)
        SMM_Window.setTabOrder(self.sim_tab_trn_n, self.sim_tab_trn_k)
        SMM_Window.setTabOrder(self.sim_tab_trn_k, self.sim_tab_add_layer_button)
        SMM_Window.setTabOrder(self.sim_tab_add_layer_button, self.sim_tab_rem_layer_button)
        SMM_Window.setTabOrder(self.sim_tab_rem_layer_button, self.sim_tab_export_button)
        SMM_Window.setTabOrder(self.sim_tab_export_button, self.sim_tab_clear_button)
        SMM_Window.setTabOrder(self.sim_tab_clear_button, self.sim_tab_sim_button)
        SMM_Window.setTabOrder(self.sim_tab_sim_button, self.sim_tab_sim_mat1)
        SMM_Window.setTabOrder(self.sim_tab_sim_mat1, self.sim_tab_sim_mat_size1)
        SMM_Window.setTabOrder(self.sim_tab_sim_mat_size1, self.sim_tab_sim_mat2)
        SMM_Window.setTabOrder(self.sim_tab_sim_mat2, self.sim_tab_sim_mat_size2)

    def retranslateUi(self, SMM_Window):
        _translate = QtCore.QCoreApplication.translate
        SMM_Window.setWindowTitle(_translate("SMM_Window", "SMM Calculator"))
        self.sim_tab_ref_label.setText(_translate("SMM_Window", "Reflection"))
        self.sim_tab_ref_n_label.setText(_translate("SMM_Window", "n"))
        self.sim_tab_ref_n.setStatusTip(_translate("SMM_Window", "Real refractive index in reflection region"))
        self.sim_tab_ref_n.setText(_translate("SMM_Window", "1"))
        self.sim_tab_ref_k_label.setText(_translate("SMM_Window", "k"))
        self.sim_tab_ref_k.setStatusTip(_translate("SMM_Window", "Complex refractive index in reflection region"))
        self.sim_tab_ref_k.setText(_translate("SMM_Window", "0"))
        self.sim_tab_sim_size_label.setText(_translate("SMM_Window", "Size (nm)"))
        self.sim_tab_sim_mat_label.setText(_translate("SMM_Window", "Material"))
        self.sim_tab_trn_label.setText(_translate("SMM_Window", "Transmission"))
        self.sim_tab_trn_n_label.setText(_translate("SMM_Window", "n"))
        self.sim_tab_trn_n.setStatusTip(_translate("SMM_Window", "Real refractive index in transmission region"))
        self.sim_tab_trn_n.setText(_translate("SMM_Window", "1"))
        self.sim_tab_trn_k_label.setText(_translate("SMM_Window", "k"))
        self.sim_tab_trn_k.setStatusTip(_translate("SMM_Window", "Complex refractive index in transmission region"))
        self.sim_tab_trn_k.setText(_translate("SMM_Window", "0"))
        self.sim_tab_add_layer_button.setStatusTip(_translate("SMM_Window", "Add a layer to the bottom of the stack"))
        self.sim_tab_add_layer_button.setText(_translate("SMM_Window", "Add Layer"))
        self.sim_tab_rem_layer_button.setStatusTip(_translate("SMM_Window", "Remove bottom layer from the stack"))
        self.sim_tab_rem_layer_button.setText(_translate("SMM_Window", "Remove Layer"))
        self.sim_tab_export_button.setStatusTip(_translate("SMM_Window", "Export the stored simulation results"))
        self.sim_tab_export_button.setText(_translate("SMM_Window", "Export"))
        self.sim_tab_clear_button.setStatusTip(_translate("SMM_Window", "Clear all stored simulation results"))
        self.sim_tab_clear_button.setText(_translate("SMM_Window", "Clear"))
        self.sim_tab_sim_button.setStatusTip(_translate("SMM_Window", "Perform Simulation"))
        self.sim_tab_sim_button.setText(_translate("SMM_Window", "Simulate"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.simulation_tab), _translate("SMM_Window", "Simulation"))
        self.opt_tab_ref_label.setText(_translate("SMM_Window", "Reflection"))
        self.opt_tab_ref_n_label.setText(_translate("SMM_Window", "n"))
        self.opt_tab_ref_n.setStatusTip(_translate("SMM_Window", "Real refractive index in reflection region"))
        self.opt_tab_ref_n.setText(_translate("SMM_Window", "1"))
        self.opt_tab_ref_k_label.setText(_translate("SMM_Window", "k"))
        self.opt_tab_ref_k.setStatusTip(_translate("SMM_Window", "Complex refractive index in reflection region"))
        self.opt_tab_ref_k.setText(_translate("SMM_Window", "0"))
        self.opt_tab_sim_mat_size_max_label.setText(_translate("SMM_Window", "Upper (nm)"))
        self.opt_tab_sim_mat_size_min_label.setText(_translate("SMM_Window", "Lower (nm)"))
        self.opt_tab_sim_mat_label.setText(_translate("SMM_Window", "Material"))
        self.opt_tab_trn_label.setText(_translate("SMM_Window", "Transmission"))
        self.opt_tab_trn_n_label.setText(_translate("SMM_Window", "n"))
        self.opt_tab_trn_n.setStatusTip(_translate("SMM_Window", "Real refractive index in transmission region"))
        self.opt_tab_trn_n.setText(_translate("SMM_Window", "1"))
        self.opt_tab_trn_k_label.setText(_translate("SMM_Window", "k"))
        self.opt_tab_trn_k.setStatusTip(_translate("SMM_Window", "Complex refractive index in transission region"))
        self.opt_tab_trn_k.setText(_translate("SMM_Window", "0"))
        self.opt_tab_add_layer_button.setStatusTip(_translate("SMM_Window", "Add a layer to the bottom of the stack"))
        self.opt_tab_add_layer_button.setText(_translate("SMM_Window", "Add Layer"))
        self.opt_tab_rem_layer_button.setStatusTip(_translate("SMM_Window", "Remove bottom layer from the stack"))
        self.opt_tab_rem_layer_button.setText(_translate("SMM_Window", "Remove Layer"))
        self.opt_tab_sim_button.setStatusTip(_translate("SMM_Window", "Perform Optimization"))
        self.opt_tab_sim_button.setText(_translate("SMM_Window", "Optimize"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.optimizatio_tab), _translate("SMM_Window", "Optimization"))
        self.simulation_label.setText(_translate("SMM_Window", "Simulation"))
        self.sim_param_ptm_label.setText(_translate("SMM_Window", "PTM"))
        self.sim_param_phi_label.setText(_translate("SMM_Window", "φ"))
        self.sim_param_theta_label.setText(_translate("SMM_Window", "θ"))
        self.sim_param_lmb_min.setStatusTip(_translate("SMM_Window", "Lower wavelength bound to simulate"))
        self.sim_param_lmb_min.setText(_translate("SMM_Window", "300"))
        self.sim_param_lmb_min.setPlaceholderText(_translate("SMM_Window", "0"))
        self.sim_param_lmb_max_label.setText(_translate("SMM_Window", "λ max (nm)"))
        self.sim_param_pte.setStatusTip(_translate("SMM_Window", "TE polarization vector component (non-normalized)"))
        self.sim_param_pte.setText(_translate("SMM_Window", "0"))
        self.sim_param_lmb_min_label.setText(_translate("SMM_Window", "λ min (nm)"))
        self.sim_param_theta.setStatusTip(_translate("SMM_Window", "Polar incidence angle"))
        self.sim_param_theta.setText(_translate("SMM_Window", "0"))
        self.sim_param_ptm.setStatusTip(_translate("SMM_Window", "TM polarization vector component (non-normalized)"))
        self.sim_param_ptm.setText(_translate("SMM_Window", "1"))
        self.sim_param_pte_label.setText(_translate("SMM_Window", "PTE"))
        self.sim_param_lmb_max.setStatusTip(_translate("SMM_Window", "Upper wavelength bound for simulation"))
        self.sim_param_lmb_max.setText(_translate("SMM_Window", "900"))
        self.sim_param_phi.setStatusTip(_translate("SMM_Window", "Azimutal incidence angle"))
        self.sim_param_phi.setText(_translate("SMM_Window", "0"))
        self.sim_param_ref_checkbox.setText(_translate("SMM_Window", "Reflection"))
        self.sim_param_trn_checkbox.setText(_translate("SMM_Window", "Transmission"))
        self.sim_param_abs_checkbox.setText(_translate("SMM_Window", "Absorption"))
        self.opt_res_text.setPlaceholderText(_translate("SMM_Window", "Optimization Results"))
        self.import_button.setStatusTip(_translate("SMM_Window", "Import data from file"))
        self.import_button.setText(_translate("SMM_Window", "Import"))
        self.menuFile.setTitle(_translate("SMM_Window", "File"))
        self.menuDatabase.setTitle(_translate("SMM_Window", "Database"))
        self.menuHelp.setTitle(_translate("SMM_Window", "Help"))
        self.actionAdd_to_Database.setText(_translate("SMM_Window", "Add to Database"))
        self.actionRemove_from_Database.setText(_translate("SMM_Window", "Remove from Database"))
        self.actionExit.setText(_translate("SMM_Window", "Exit"))
        self.actionView_Database.setText(_translate("SMM_Window", "Manage Database"))
        self.actionProperties.setText(_translate("SMM_Window", "Properties"))
        self.actionHelp.setText(_translate("SMM_Window", "Help"))
        self.actionAbout.setText(_translate("SMM_Window", "About"))
